[project]
name = "moshilibraryms"
version = "0.1.0"
description = "A Library management app"
requires-python = ">=3.13"
dependencies = [
    "django>=5.2.1",
    "mysqlclient>=2.2.7",
    "python-dotenv>=1.1.0",
]
