# Generated by Django 5.2.1 on 2025-06-17 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_initial'),
        ('user', '0002_alter_author_dod'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(related_name='books', to='user.author'),
        ),
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='catalogue.language'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(choices=[('ROMANCE', 'R'), ('COMEDY', 'C'), ('FINANCE', 'F'), ('POLITICS', 'P')], default='R', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(choices=[('YORUBA', 'Y'), ('ENGLISH', 'E'), ('FRENCH', 'F')], default='Y', max_length=10, unique=True),
        ),
    ]
