# Generated by Django 5.2.1 on 2025-06-17 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='dod',
            field=models.DateField(null=True),
        ),
    ]
