# Generated by Django 5.2.1 on 2025-07-03 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_author_dod'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
    ]
